const feelBlue = {
    "audio_features": [
        {
            "song": "Cry Me a River",
            "artist": "Nina Nesbitt",
            "danceability": 0.665,
            "energy": 0.252,
            "key": 3,
            "loudness": -8.407,
            "mode": 0,
            "speechiness": 0.0323,
            "acousticness": 0.855,
            "instrumentalness": 0,
            "liveness": 0.113,
            "valence": 0.339,
            "tempo": 121.994,
            "type": "audio_features",
            "id": "3pRtmEYL0hN9Lgn0IkNOra",
            "uri": "spotify:track:3pRtmEYL0hN9Lgn0IkNOra",
            "track_href": "https://api.spotify.com/v1/tracks/3pRtmEYL0hN9Lgn0IkNOra",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/3pRtmEYL0hN9Lgn0IkNOra",
            "duration_ms": 301145,
            "time_signature": 4
        },
        {
            "song": "Väntar På En Ängel",
            "artist": "Oskar Linnros",
            "danceability": 0.531,
            "energy": 0.569,
            "key": 8,
            "loudness": -8.194,
            "mode": 1,
            "speechiness": 0.0365,
            "acousticness": 0.0919,
            "instrumentalness": 0.0194,
            "liveness": 0.294,
            "valence": 0.41,
            "tempo": 89.919,
            "type": "audio_features",
            "id": "7Am8I3Yk0ElEG7Z0mNWxkk",
            "uri": "spotify:track:7Am8I3Yk0ElEG7Z0mNWxkk",
            "track_href": "https://api.spotify.com/v1/tracks/7Am8I3Yk0ElEG7Z0mNWxkk",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/7Am8I3Yk0ElEG7Z0mNWxkk",
            "duration_ms": 269840,
            "time_signature": 4
        },
        {
            "song": "Soptippsvärld",
            "artist": "Titiyo",
            "danceability": 0.707,
            "energy": 0.643,
            "key": 1,
            "loudness": -8.804,
            "mode": 1,
            "speechiness": 0.0331,
            "acousticness": 0.0545,
            "instrumentalness": 0.00000569,
            "liveness": 0.125,
            "valence": 0.651,
            "tempo": 108.008,
            "type": "audio_features",
            "id": "5mld5kbGFor8dhkQEYtp4E",
            "uri": "spotify:track:5mld5kbGFor8dhkQEYtp4E",
            "track_href": "https://api.spotify.com/v1/tracks/5mld5kbGFor8dhkQEYtp4E",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/5mld5kbGFor8dhkQEYtp4E",
            "duration_ms": 227191,
            "time_signature": 4
        },
        {
            "song": "Stepping Stone",
            "artist": "Duffy",
            "danceability": 0.694,
            "energy": 0.523,
            "key": 2,
            "loudness": -6.407,
            "mode": 0,
            "speechiness": 0.0254,
            "acousticness": 0.875,
            "instrumentalness": 0.000172,
            "liveness": 0.352,
            "valence": 0.472,
            "tempo": 97.985,
            "type": "audio_features",
            "id": "3g9nxeJPQM4CxhHt1iNlB4",
            "uri": "spotify:track:3g9nxeJPQM4CxhHt1iNlB4",
            "track_href": "https://api.spotify.com/v1/tracks/3g9nxeJPQM4CxhHt1iNlB4",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/3g9nxeJPQM4CxhHt1iNlB4",
            "duration_ms": 209453,
            "time_signature": 4
        },
        {
            "song": "SOS",
            "artist": "Avicii, Aloe Blacc",
            "danceability": 0.802,
            "energy": 0.645,
            "key": 5,
            "loudness": -6.181,
            "mode": 0,
            "speechiness": 0.0715,
            "acousticness": 0.272,
            "instrumentalness": 0,
            "liveness": 0.119,
            "valence": 0.376,
            "tempo": 100.001,
            "type": "audio_features",
            "id": "0n2nEtLP3OzDdi12ziIekx",
            "uri": "spotify:track:0n2nEtLP3OzDdi12ziIekx",
            "track_href": "https://api.spotify.com/v1/tracks/0n2nEtLP3OzDdi12ziIekx",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/0n2nEtLP3OzDdi12ziIekx",
            "duration_ms": 157202,
            "time_signature": 4
        },
        {
            "song": "Can't Tell",
            "artist": "Niklas Danielsen",
            "danceability": 0.706,
            "energy": 0.481,
            "key": 6,
            "loudness": -8.755,
            "mode": 0,
            "speechiness": 0.0724,
            "acousticness": 0.151,
            "instrumentalness": 0,
            "liveness": 0.272,
            "valence": 0.558,
            "tempo": 72.471,
            "type": "audio_features",
            "id": "0PBPcrjwteq8HjCaEWp0pF",
            "uri": "spotify:track:0PBPcrjwteq8HjCaEWp0pF",
            "track_href": "https://api.spotify.com/v1/tracks/0PBPcrjwteq8HjCaEWp0pF",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/0PBPcrjwteq8HjCaEWp0pF",
            "duration_ms": 180555,
            "time_signature": 4
        },
        {
            "song": "The Weight Is Gone",
            "artist": "Albin Lee Meldau",
            "danceability": 0.835,
            "energy": 0.627,
            "key": 10,
            "loudness": -6.515,
            "mode": 0,
            "speechiness": 0.0342,
            "acousticness": 0.0604,
            "instrumentalness": 0.000128,
            "liveness": 0.208,
            "valence": 0.902,
            "tempo": 105.011,
            "type": "audio_features",
            "id": "3lYntvQ6qbfSZY4pKTKEwD",
            "uri": "spotify:track:3lYntvQ6qbfSZY4pKTKEwD",
            "track_href": "https://api.spotify.com/v1/tracks/3lYntvQ6qbfSZY4pKTKEwD",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/3lYntvQ6qbfSZY4pKTKEwD",
            "duration_ms": 212440,
            "time_signature": 4
        },
        {
            "song": "Hanging On",
            "artist": "Active Child",
            "danceability": 0.572,
            "energy": 0.535,
            "key": 8,
            "loudness": -8.919,
            "mode": 1,
            "speechiness": 0.0284,
            "acousticness": 0.284,
            "instrumentalness": 0.0587,
            "liveness": 0.128,
            "valence": 0.252,
            "tempo": 134.962,
            "type": "audio_features",
            "id": "6o4lFpp8OAFhBqGQbWyAob",
            "uri": "spotify:track:6o4lFpp8OAFhBqGQbWyAob",
            "track_href": "https://api.spotify.com/v1/tracks/6o4lFpp8OAFhBqGQbWyAob",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/6o4lFpp8OAFhBqGQbWyAob",
            "duration_ms": 321453,
            "time_signature": 4
        },
        {
            "song": "I Owe You Nothing",
            "artist": "Seinabo Sey",
            "danceability": 0.353,
            "energy": 0.44,
            "key": 6,
            "loudness": -8.423,
            "mode": 0,
            "speechiness": 0.0423,
            "acousticness": 0.189,
            "instrumentalness": 0.00312,
            "liveness": 0.344,
            "valence": 0.337,
            "tempo": 81.799,
            "type": "audio_features",
            "id": "7gppHT2hATlO5ONxcFy06T",
            "uri": "spotify:track:7gppHT2hATlO5ONxcFy06T",
            "track_href": "https://api.spotify.com/v1/tracks/7gppHT2hATlO5ONxcFy06T",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/7gppHT2hATlO5ONxcFy06T",
            "duration_ms": 204707,
            "time_signature": 4
        },
        {
            "song": "Youth",
            "artist": "Sean Mendes",
            "danceability": 0.534,
            "energy": 0.596,
            "key": 6,
            "loudness": -6.653,
            "mode": 0,
            "speechiness": 0.117,
            "acousticness": 0.56,
            "instrumentalness": 0,
            "liveness": 0.133,
            "valence": 0.324,
            "tempo": 100.121,
            "type": "audio_features",
            "id": "1h0yImRPIVAjhhHeNVlTuC",
            "uri": "spotify:track:1h0yImRPIVAjhhHeNVlTuC",
            "track_href": "https://api.spotify.com/v1/tracks/1h0yImRPIVAjhhHeNVlTuC",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/1h0yImRPIVAjhhHeNVlTuC",
            "duration_ms": 190867,
            "time_signature": 4
        },
        {
            "song": "No Fixed Abode",
            "artist": "Mitch James",
            "danceability": 0.689,
            "energy": 0.317,
            "key": 4,
            "loudness": -7.631,
            "mode": 1,
            "speechiness": 0.0637,
            "acousticness": 0.83,
            "instrumentalness": 0,
            "liveness": 0.0982,
            "valence": 0.469,
            "tempo": 90.156,
            "type": "audio_features",
            "id": "2kzWnWUUsn3o44PbOzFSjc",
            "uri": "spotify:track:2kzWnWUUsn3o44PbOzFSjc",
            "track_href": "https://api.spotify.com/v1/tracks/2kzWnWUUsn3o44PbOzFSjc",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/2kzWnWUUsn3o44PbOzFSjc",
            "duration_ms": 204081,
            "time_signature": 4
        },
        {
            "song": "Innan Du Går",
            "artist": "Kaah",
            "danceability": 0.717,
            "energy": 0.425,
            "key": 5,
            "loudness": -11.271,
            "mode": 0,
            "speechiness": 0.0437,
            "acousticness": 0.588,
            "instrumentalness": 0.000161,
            "liveness": 0.0762,
            "valence": 0.837,
            "tempo": 170.749,
            "type": "audio_features",
            "id": "4yuS8jcTcKyRCN4owZXIhH",
            "uri": "spotify:track:4yuS8jcTcKyRCN4owZXIhH",
            "track_href": "https://api.spotify.com/v1/tracks/4yuS8jcTcKyRCN4owZXIhH",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/4yuS8jcTcKyRCN4owZXIhH",
            "duration_ms": 287520,
            "time_signature": 4
        },
        {
            "song": "Till Dom Ensamma",
            "artist": "Mauro Scocco",
            "danceability": 0.465,
            "energy": 0.546,
            "key": 1,
            "loudness": -9.649,
            "mode": 1,
            "speechiness": 0.0271,
            "acousticness": 0.443,
            "instrumentalness": 0,
            "liveness": 0.133,
            "valence": 0.471,
            "tempo": 164.131,
            "type": "audio_features",
            "id": "31AMbxkc5KHNtBSmuNww60",
            "uri": "spotify:track:31AMbxkc5KHNtBSmuNww60",
            "track_href": "https://api.spotify.com/v1/tracks/31AMbxkc5KHNtBSmuNww60",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/31AMbxkc5KHNtBSmuNww60",
            "duration_ms": 300373,
            "time_signature": 4
        }
    ]
}