const feelBlue = {
    "audio_features": [
        {
            "song": "Cry Me a River",
            "artist": "Nina Nesbitt",
            "danceability": 0.665,
            "energy": 0.252,
            "key": 3,
            "loudness": -8.407,
            "mode": 0,
            "speechiness": 0.0323,
            "acousticness": 0.855,
            "instrumentalness": 0,
            "liveness": 0.113,
            "valence": 0.339,
            "tempo": 121.994,
            "type": "audio_features",
            "id": "3pRtmEYL0hN9Lgn0IkNOra",
            "uri": "spotify:track:3pRtmEYL0hN9Lgn0IkNOra",
            "track_href": "https://api.spotify.com/v1/tracks/3pRtmEYL0hN9Lgn0IkNOra",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/3pRtmEYL0hN9Lgn0IkNOra",
            "duration_ms": 301145,
            "time_signature": 4
        },
        {
            "song": "Väntar På En Ängel",
            "artist": "Oskar Linnros",
            "danceability": 0.531,
            "energy": 0.569,
            "key": 8,
            "loudness": -8.194,
            "mode": 1,
            "speechiness": 0.0365,
            "acousticness": 0.0919,
            "instrumentalness": 0.0194,
            "liveness": 0.294,
            "valence": 0.41,
            "tempo": 89.919,
            "type": "audio_features",
            "id": "7Am8I3Yk0ElEG7Z0mNWxkk",
            "uri": "spotify:track:7Am8I3Yk0ElEG7Z0mNWxkk",
            "track_href": "https://api.spotify.com/v1/tracks/7Am8I3Yk0ElEG7Z0mNWxkk",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/7Am8I3Yk0ElEG7Z0mNWxkk",
            "duration_ms": 269840,
            "time_signature": 4
        },
        {
            "song": "Flames",
            "artist": "David Guetta",
            "danceability": 0.609,
            "energy": 0.726,
            "key": 5,
            "loudness": -4.346,
            "mode": 0,
            "speechiness": 0.0414,
            "acousticness": 0.0723,
            "instrumentalness": 0.00000845,
            "liveness": 0.0895,
            "valence": 0.362,
            "tempo": 93.958,
            "type": "audio_features",
            "id": "33IOhptvC2Qoy2UhjiHXLV",
            "uri": "spotify:track:33IOhptvC2Qoy2UhjiHXLV",
            "track_href": "https://api.spotify.com/v1/tracks/33IOhptvC2Qoy2UhjiHXLV",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/33IOhptvC2Qoy2UhjiHXLV",
            "duration_ms": 195000,
            "time_signature": 4
        },
        {
            "song": "Stepping Stone",
            "artist": "Duffy",
            "danceability": 0.694,
            "energy": 0.523,
            "key": 2,
            "loudness": -6.407,
            "mode": 0,
            "speechiness": 0.0254,
            "acousticness": 0.875,
            "instrumentalness": 0.000172,
            "liveness": 0.352,
            "valence": 0.472,
            "tempo": 97.985,
            "type": "audio_features",
            "id": "3g9nxeJPQM4CxhHt1iNlB4",
            "uri": "spotify:track:3g9nxeJPQM4CxhHt1iNlB4",
            "track_href": "https://api.spotify.com/v1/tracks/3g9nxeJPQM4CxhHt1iNlB4",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/3g9nxeJPQM4CxhHt1iNlB4",
            "duration_ms": 209453,
            "time_signature": 4
        },
        {
            "song": "SOS",
            "artist": "Avicii, Aloe Blacc",
            "danceability": 0.802,
            "energy": 0.645,
            "key": 5,
            "loudness": -6.181,
            "mode": 0,
            "speechiness": 0.0715,
            "acousticness": 0.272,
            "instrumentalness": 0,
            "liveness": 0.119,
            "valence": 0.376,
            "tempo": 100.001,
            "type": "audio_features",
            "id": "0n2nEtLP3OzDdi12ziIekx",
            "uri": "spotify:track:0n2nEtLP3OzDdi12ziIekx",
            "track_href": "https://api.spotify.com/v1/tracks/0n2nEtLP3OzDdi12ziIekx",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/0n2nEtLP3OzDdi12ziIekx",
            "duration_ms": 157202,
            "time_signature": 4
        },
        {
            "song": "Hanging On",
            "artist": "Active Child",
            "danceability": 0.572,
            "energy": 0.535,
            "key": 8,
            "loudness": -8.919,
            "mode": 1,
            "speechiness": 0.0284,
            "acousticness": 0.284,
            "instrumentalness": 0.0587,
            "liveness": 0.128,
            "valence": 0.252,
            "tempo": 134.962,
            "type": "audio_features",
            "id": "6o4lFpp8OAFhBqGQbWyAob",
            "uri": "spotify:track:6o4lFpp8OAFhBqGQbWyAob",
            "track_href": "https://api.spotify.com/v1/tracks/6o4lFpp8OAFhBqGQbWyAob",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/6o4lFpp8OAFhBqGQbWyAob",
            "duration_ms": 321453,
            "time_signature": 4
        },
        {
            "song": "I Owe You Nothing",
            "artist": "Seinabo Sey",
            "danceability": 0.353,
            "energy": 0.44,
            "key": 6,
            "loudness": -8.423,
            "mode": 0,
            "speechiness": 0.0423,
            "acousticness": 0.189,
            "instrumentalness": 0.00312,
            "liveness": 0.344,
            "valence": 0.337,
            "tempo": 81.799,
            "type": "audio_features",
            "id": "7gppHT2hATlO5ONxcFy06T",
            "uri": "spotify:track:7gppHT2hATlO5ONxcFy06T",
            "track_href": "https://api.spotify.com/v1/tracks/7gppHT2hATlO5ONxcFy06T",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/7gppHT2hATlO5ONxcFy06T",
            "duration_ms": 204707,
            "time_signature": 4
        },
        {
            "song": "Youth",
            "artist": "Sean Mendes",
            "danceability": 0.534,
            "energy": 0.596,
            "key": 6,
            "loudness": -6.653,
            "mode": 0,
            "speechiness": 0.117,
            "acousticness": 0.56,
            "instrumentalness": 0,
            "liveness": 0.133,
            "valence": 0.324,
            "tempo": 100.121,
            "type": "audio_features",
            "id": "1h0yImRPIVAjhhHeNVlTuC",
            "uri": "spotify:track:1h0yImRPIVAjhhHeNVlTuC",
            "track_href": "https://api.spotify.com/v1/tracks/1h0yImRPIVAjhhHeNVlTuC",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/1h0yImRPIVAjhhHeNVlTuC",
            "duration_ms": 190867,
            "time_signature": 4
        },
        {
            "song": "Lonely Together",
            "artist": "Avicii (feat. Rita Ora",
            "danceability": 0.655,
            "energy": 0.666,
            "key": 5,
            "loudness": -5.309,
            "mode": 1,
            "speechiness": 0.0612,
            "acousticness": 0.134,
            "instrumentalness": 0.0000212,
            "liveness": 0.0683,
            "valence": 0.272,
            "tempo": 102.977,
            "type": "audio_features",
            "id": "75NhhYjHO43mvZgYtnXgti",
            "uri": "spotify:track:75NhhYjHO43mvZgYtnXgti",
            "track_href": "https://api.spotify.com/v1/tracks/75NhhYjHO43mvZgYtnXgti",
            "analysis_url": "https://api.spotify.com/v1/audio-analysis/75NhhYjHO43mvZgYtnXgti",
            "duration_ms": 181812,
            "time_signature": 4
        }
    ]
}